name: Irrigation Scripts Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Budapest"
      - uses: actions/checkout@v3
      
      - name: Git Config
        run: |
          git config user.name "FodorHOME Irrigation"
          git config user.email "home@fodor.pro"

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: stable
          
      - name: Compile Script
        run: dart compile exe ./bin/script.dart

      - name: Publish changes
        run: |
          git add bin
          git commit -m "Upload new build"
          git push origin main