name: Irrigation CRON Run

on:
  schedule:
   - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Budapest"
      - uses: actions/checkout@v3
      
      - name: Git Config
        run: |
          git config user.name "FodorHOME Irrigation"
          git config user.email "home@fodor.pro"
          
      - name: Download and unpack last week's weather data from OMSZ
        run: |
          rm -rf lastweek
          mkdir -p lastweek
          cd lastweek
          wget https://odp.met.hu/climate/observations_hungary/daily/recent/HABP_1D_46400_akt.zip
      
      - name: Download and unpack yesterday's weather data from OMSZ
        run: |
          rm -rf yesterday
          mkdir -p yesterday
          cd yesterday
          wget https://odp.met.hu/climate/observations_hungary/hourly/now/HABP_1H_46400_now.zip

      - name: Read secrets
        run: echo "${{ secrets.AUTH_JSON_BASE64 }}" | base64 -d > auth.json
          
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq lastweek/HABP_1D_46400_akt.zip -d lastweek
          
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq yesterday/HABP_1H_46400_now.zip -d yesterday

      - name: Delete original zips
        run: |
          rm -f "lastweek/HABP_1D_46400_akt.zip"
          rm -f "yesterday/HABP_1H_46400_now.zip"

      - name: Run Script
        run: ./bin/script.exe

      - name: Publish changes
        run: |
          git add docs
          git commit -m "Upload new data"
          git push origin main
      
